"""add_project_sharing

Revision ID: 4aa5da27aa04
Revises: 002
Create Date: 2026-01-25 08:43:13.759208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa5da27aa04'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('share_enabled', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_projects_share_token'), 'projects', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_share_token'), table_name='projects')
    op.drop_column('projects', 'share_token')
    op.drop_column('projects', 'share_enabled')
    # ### end Alembic commands ###
